services:
  backend:
    image: ghcr.io/nbqduong/e-sim-backend:v0.0.3
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/esim
      - FRONTEND_DIST_DIR=/home/worker/source/frontend__output/
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: esim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 
    restart: always

volumes:
  pgdata: