version: "3"

tasks:
  default:
    desc: Clone repo, init submodules, build and run
    cmds:
      - task: local

  build_fronted:
    desc: Build frontend only
    cmds:
      - git submodule update --init
      - docker compose up frontend --build

  local:
    desc: Init submodules and build/run all services
    cmds:
      - task: build_fronted
      - docker compose up backend --build

  deploy:
    desc: Deploy backend 
    cmds:
      - docker compose -f docker-compose.prod.yml up

  release:
    desc: Build and release backend image to GitHub Container Registry
    cmds:
      - echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
      - task: local
      - docker tag e-sim-backend "ghcr.io/$DOCKER_USERNAME/e-sim-backend:latest"
      - docker push "ghcr.io/$DOCKER_USERNAME/e-sim-backend:latest"
      - docker logout ghcr.io

  launch_backend_dev:
    desc: Serve backend only (for development)
    cmds:
      - task: build_fronted
      - docker compose run --rm -it --service-ports -v $(pwd)/backend:/home/worker/source backend bash


